#!/bin/bash

DIR=/usr/share/backgrounds/wallpapers-1
PICS=($(find ${DIR} -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" \)))
RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}


change_swww(){
  pkill swaybg
  swww query || swww init
  swww img ${RANDOMPICS} --transition-fps 30 --transition-type any --transition-duration 3
}

change_current(){
  if pidof swaybg >/dev/null; then
    change_swww
  else
    change_swww
  fi
}

case "$1" in
	"swww")
		change_swww
		;;
  *)
		change_current
		;;
esac