#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

#wallpaper load
#${SCRIPTSDIR}/wall &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &




