#!/bin/bash

## Files
CONFIG="$HOME/.config/hypr/wofifull/config"
STYLE="$HOME/.config/hypr/wofifull/style.css"
COLORS="$HOME/.config/hypr/wofifull/colors"
iDIR="$HOME/.config/hypr/mako/icons"

## Wofi Command
wofi_command="wofi --show dmenu \
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=350 --height=380 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"


notification(){
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/music.png" "Now Playing: Online Music" 
}

menu(){
printf "1. Technolover-Vocal-Trance Radio\n"
printf "2. DI.fm VocalTrance Radio\n"
printf "3. PulsRadio Trance Radio\n"
printf "4. Youtube Aurosonic-Euforia Album\n"
printf "5. TranceBase.FM\n"
printf "6. SunshineLive-VT\n"
printf "7. DFM-Trance\n"
printf "8. Youtube-VocalTrance\n"
printf "9. Best VT youtube"
}
main() {
choice=$(menu | ${wofi_command} | cut -d. -f1)
case $choice in
1)
    notification
    mpv "https://stream.technolovers.fm/vocal-trance?ref=radiobrowser"
    return
    ;;
2)
   notification
   mpv "http://prem1.di.fm/vocaltrance_hi?907d839cb7ee13512903cbcf"
   return
;; 
3)
  notification
   mpv "https://sc2.gergosnet.com:80/pulstranceHD.mp3"
   return
   ;;
4)
   notification ;
   mpv --vid=no "https://youtu.be/4duklTPS084"
   return
   ;;
5)
  notification ;
  mpv "http://listener3.mp3.tb-group.fm:80/trb.mp3"
  return
  ;;
6)
  notification ;
  mpv "https://stream.sunshine-live.de/vocaltrance/mp3-192"
  return
  ;;
7)
  notification ;
  mpv "https://dfm-trance.hostingradio.ru/trance96.aacp"
  return
;;
8)
  notification ;
  mpv --shuffle  --vid=no "https://youtu.be/42ao7PafV-s"
  return
  ;;
9)
  notification ;
  mpv --shuffle  --vid=no "https://youtube.com/playlist?list=PLUHBf5XMtOmRMC__VHZw3xmjyZqQko2_n"
  return
;;
esac
}

pkill -f http && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/music.png" "Online Music stopped" || main
